services:
  - type: web
    name: kakeibo-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: kakeibo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: kakeibo-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: kakeibo-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: kakeibo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: kakeibo-db
          property: password
      - key: COOKIE_SECURE
        value: true

databases:
  - name: kakeibo-db
    databaseName: kakeibo_db
    user: kakeibo_user
    plan: free
