services:
  - type: web
    name: kakeibo-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kakeibo-db
          property: connectionString
      - key: COOKIE_SECURE
        value: true

databases:
  - name: kakeibo-db
    databaseName: kakeibo_db
    user: kakeibo_user
    plan: free
